include: https://raw.githubusercontent.com/SciML/RebuildAction/master/rebuild.yml
variables:
  CONTENT_DIR: tutorials
  EXCLUDE: exercises/02-workshop-solutions, models/06-pendulum_bayesian_inference
  NEEDS_GPU: advanced/01-beeler-reuter
  GITHUB_REPOSITORY: SciML/DiffEqTutorials.jl
